import "@fontsource-variable/pixelify-sans";
import "../globals.css";

import ThemeProvider from "@/components/providers/theme";
import QueryClientProvider from "@/components/providers/queryClient";
import Header from "@/app/game/header";

export const metadata = {
  title: "Juego Memorice",
  description: "Generated by create next app",
};

export default function GameLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="theme">
        <ThemeProvider>
          <QueryClientProvider>
            <Header />
            {children}
          </QueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
